name: SAM Validate, Build, Test
on:
  push:
    branches:
      - feature/sam
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: aws-actions/setup-sam@v11
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build --use-container
      - run: sam deploy --template-file template.yaml --stack-name dinesh --s3-bucket testingsbucket --capabilities CAPABILITY_IAM1